# Generated by Django 5.2.1 on 2025-06-10 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Catégorie'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Localisation'},
        ),
        migrations.AlterModelOptions(
            name='movement',
            options={'verbose_name': 'Mouvement'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Produit'},
        ),
        migrations.AlterModelOptions(
            name='provider',
            options={'verbose_name': 'Fournisseur'},
        ),
        migrations.AlterModelOptions(
            name='reason',
            options={'verbose_name': 'Raison'},
        ),
        migrations.AlterModelOptions(
            name='shoppinglist',
            options={'verbose_name': 'Liste de course'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': 'Stockage'},
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='open_stock.category'),
        ),
    ]
