# Generated by Django 5.2.1 on 2025-06-10 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_stock', '0002_alter_category_options_alter_location_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
