# Generated by Django 5.2.1 on 2025-06-10 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('open_stock', '0003_shoppinglist_created_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='alarm_min_part',
            new_name='min_part_alarm',
        ),
    ]
