# Generated by Django 5.2.1 on 2025-06-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_stock', '0004_rename_alarm_min_part_product_min_part_alarm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='min_part_alarm',
        ),
        migrations.AddField(
            model_name='product',
            name='min_count_alarm',
            field=models.IntegerField(default=0),
        ),
    ]
