# Generated by Django 5.2.1 on 2025-06-10 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('open_stock', '0005_remove_product_min_part_alarm_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='min_count_alarm',
            new_name='count_mini_alarm',
        ),
    ]
