# Generated by Django 5.2.1 on 2025-06-10 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_stock', '0006_rename_min_count_alarm_product_count_mini_alarm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
