# Generated by Django 5.2.1 on 2025-06-11 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_stock', '0009_alter_category_description_alter_location_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='count_mini_alarm',
            field=models.IntegerField(default=0, verbose_name='Alarme stock mini'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='shoppinglist',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
