# Generated by Django 5.2.1 on 2025-06-11 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_stock', '0010_company_slug_provider_slug_alter_company_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Compagnie'},
        ),
        migrations.AddField(
            model_name='location',
            name='Company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='open_stock.company'),
        ),
    ]
