# Generated by Django 5.2.1 on 2025-06-11 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('open_stock', '0011_alter_company_options_location_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='Company',
            new_name='company',
        ),
    ]
