# Generated by Django 5.2.1 on 2025-06-11 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_stock', '0012_rename_company_location_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='movement',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movement',
            name='reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reasons', to='open_stock.reason'),
        ),
        migrations.AddField(
            model_name='movement',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='movement',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reason',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='movement',
            name='location_dest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='open_stock.location'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='location_src',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='open_stock.location'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='provider_src',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='open_stock.provider'),
        ),
    ]
