# Generated by Django 5.2.1 on 2025-06-11 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_stock', '0013_movement_created_date_movement_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='location_dest',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='open_stock.location'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='location_src',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='open_stock.location'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='provider_src',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='open_stock.provider'),
        ),
    ]
