# Generated by Django 6.0.1 on 2026-02-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('open_stock', '0016_category_created_at_category_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='count_mini_alarm',
            field=models.IntegerField(default=1, verbose_name='Alarme stock mini'),
        ),
    ]
